$(document).ready(function() {

  // NOTICE: This is your magic 8 ball object!
  var magic8Ball = {};

  // TODO: STEP 1
  /* 
    1a. Declare AT LEAST four different variables.
    1b. Store a magic 8 ball answer in each variable.
    1c. Which data type is being stored as the value in your variables? Answer here: 
    1d. Delete the strings in the magic8Ball.listOfAnswers array below and place your new variables in there instead.

    Hint: you should not be declaring anything new besides the variables from Step 1a.
  */

  magic8Ball.listOfAnswers = ["No", "Yes", "I don't think so...", "Of course!", "Indubitably", "In your dreams."];

  $("#answer").hide();

  magic8Ball.askQuestion = function(question) {
    $("#8ball").effect("shake");

    $("#8ball").attr("src", "https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/09/magic8ballAnswer.png");

    // TODO: STEP 2
  /* 
    2a. Change the number inside of the fadeIn() function below, refresh your magic 8 ball page, and watch what happens.
    2b. Do it again, but with a different number.
    2c. Whoaaaa... why did that happen?
        Answer:



    2d. Replace that number with any other number besides 4000 and leave it so that I can see you did it lol.

    Hint: If you don't know how to answer 2c, look at this link and explain the first parameter to me in your own words:
    https://www.w3schools.com/jquery/eff_fadein.asp
  */
    $("#answer").fadeIn(4000);

    var randomNumber = Math.random();

    // FUN FACT: "this" is a keyword that references the object currently executing the code- meaning it's
    // referencing the listOfAnswers array in your magic 8 ball object
    var randomNumberForListOfAnswers = randomNumber * this.listOfAnswers.length;

    // TODO: STEP 3
    /*
      The variable below, randomIndex, is a random number generated by using Math.random() and Math.floor().

      3a. Replace randomIndex in var answer = this.listOfAnswers[randomIndex]; with 0
      3b. What happened?
          Answer:



      3c. Try putting 1. What happened then?
          Answer:



      3d. If you hadn't already explained above, why did the things that happened for 3b and 3c happen? If you already
          explained, please write a funny joke in the answer below.
          Answer:



      3e. Replace whatever hardcoded number you have put with the randomIndex so that we don't break your beautiful magic 8 ball.
    */
    var randomIndex = Math.floor(randomNumberForListOfAnswers);

    var answer = this.listOfAnswers[randomIndex];

    $("#answer").text(answer);

    // TODO: STEP 4
    /*
      As we've learned, console.log() prints whatever we want to the console.

      4a. Where the heck are we going to see the question and answer printed from the two
          console.log() below??
          Answer:



          Hint: Right click your magic 8 ball page, select "Inspect", and look at the tab options on the top of the Chrome Dev
          Tools panel that pops up. I have a feeling that you're going to be looking at the Elements tab upon first opening it.
    */
    console.log(question);
    console.log(answer);
  };

  // TODO: STEP 5
  /*
   Almost done!

  5a. Please write what your magic 8 ball contents should be now that there's been some additions to it.
      For example, it could look like:

      myObject = {
        key1: 'value',
        otherKey: 24,
        yetAnotherKey: function () {

        }
      }

      Your Beautiful Object Drawing:





      Hint: If you have no clue, you know a way to view things in the code now. Look up! :)
      Hint 2: If you're still stuck after 10 minutes, come ask me what's up and I'd be happy to help.
  */

  var onClick = function() {

    $("#answer").hide();

    // TODO: STEP 6
    /*
      6a. Go online and find a picture or gif, get the link, and replace the link below.
      6b. Call me over to see it in action because I want to laugh about it.
    */
    $("#8ball").attr("src", "https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/09/magic8ballQuestion.png");


    setTimeout(function(){
      var question = prompt("ASK A YES/NO QUESTION!");
      magic8Ball.askQuestion(question);
    }, 500);


  };

  $("#questionButton").click(onClick);

});

  // TODO: STEP 7
  /*
    7a. Go to the style.css folder and mess with some of the styling. It does not need to look good at all, just change something and see what happens!
        This one is more for fun; if you're sick of working on this, you may change two properties and turn it in.

    If you want to understand more about CSS styling, visit: https://www.w3schools.com/html/html_css.asp
  */